const Projects = [
  {
    type: "raising",
    title: "XÂY DỰNG MÔ HÌNH KINH TẾ VƯỜN",
    date: "01/11/2023 - 01/11/2025 (2 năm)",
    place: "cụm dân cư Pà-Căng mới",
    linkYT: "https://www.youtube.com/embed/z9dccqTJIVs",
    des: "Mỗi hộ có diện tích vườn trên 500m2. Có điện nước đầy đủ. Hơn nữa bà con có tập quán trồng trọt và chăn nuôi. Dự án nhằm xây dựng mô hình trồng trọt và chăn nuôi quy mô nhỏ trong cụm dân cư. Dự án sẽ đồng hành cùng bà con trong quá trình xây dựng, phát triển mô hình. Qua đó, chia sẻ kiến thức khoa họa và kỹ năng làm vườn, giúp bà con hiểu sâu sắc về làm kinh tế vườn và tự xây dựng được mô hình kinh tế vườn cho gia đình của mình. Kết quả là vườn nhà được sử dụng hiệu quả, mức sống được nâng cao. Hơn nữa, góp phần làm môi trường xanh sạch đẹp.",
    amoutOfLikes: "179",
    pitchFile: "",
    planFile: "",
    cost: "",
  },
  {
    type: "raising",
    title: "XÂY DỰNG XƯỞNG SẢN XUẤT PHÂN HỮU CƠ",
    date: "01/11/2023 ~ 01/11/2025 (2 năm)",
    place: "cụm dân cư Pà-Căng mới",
    linkYT: "https://www.youtube.com/embed/z9dccqTJIVs",
    des: "Phân bón hữu cơ là yếu tố quan trọng quyết định chất lượng và sản lượng cây trồng. Dự án nhằm tái sử dụng các chất thải gia súc gia cầm, rác thải gia đình, rác thải nông nghiệp trong làng để làm nguồn phân cung cấp cho các mô hình kinh tế vườn và trang trại của bà con. Kết quả là bà con có phân bón hữu cơ chất lượng cho vườn của mình với chi phí thấp. Hơn nữa, bà con hiểu được quy trình làm rác và giá trị của rác, bà con sẽ tận dụng chúng cho việc phát triển nông nghiệp. Từ đó góp phần làm cho môi trường trong làng xanh sạch đẹp.",
    amoutOfLikes: "212",
    pitchFile: "",
    planFile: "",
    cost: "",
  },
  {
    type: "raising",
    title: "Yemen: On the brink of starvation",
    date: "10/2023~10/2028",
    place: "",
    linkYT: "https://www.youtube.com/embed/npk7tfKyXok?si=E1ubB7RWUvoCaCLX",
    des: "The war in Yemen, which began early last year when the government was overthrown by rebel forces, has pushed the country to the brink of famine. This video contains distressing scenes from the start. See more from BBC Our World's documentary Starving Yemen this weekend on BBC World, BBC News and iPlayer.",
    amoutOfLikes: "24k",
    pitchFile: "https://www.facebook.com/",
    planFile: "https://www.facebook.com/",
    cost: "",
  },
  {
    type: "raising",
    title: "Yemen: On the brink of starvation",
    date: "10/2023~10/2028",
    place: "",
    linkYT: "https://www.youtube.com/embed/npk7tfKyXok?si=E1ubB7RWUvoCaCLX",
    des: "The war in Yemen, which began early last year when the government was overthrown by rebel forces, has pushed the country to the brink of famine. This video contains distressing scenes from the start. See more from BBC Our World's documentary Starving Yemen this weekend on BBC World, BBC News and iPlayer.",
    amoutOfLikes: "24k",
    pitchFile: "https://www.facebook.com/",
    planFile: "https://www.facebook.com/",
    cost: "",
  },
  {
    type: "running",
    title:
      "Quanglinhvlogs || Khoan Giếng Nước Sạch Cho Người Dân Bản Địa Châu Phi",
    date: "10/2023~10/2028",
    place: "",
    linkYT: "https://www.youtube.com/embed/LXcWjzaMwqE?si=6ubyy8q_rcOhWl15",
    des: "Clean water changes everything. charity: water brings clean and safe drinking water to people in need around the world, improving health, education, and opportunity - especially for women and children. 100% of public donations go directly to clean water projects. Clean water changes everything. charity: water brings clean and safe drinking water to people in need around the world, improving health, education, and opportunity - especially for women and children. 100% of public donations go directly to clean water projects.",
    amoutOfLikes: "106k",
    pitchFile: "https://www.facebook.com/",
    planFile: "https://www.facebook.com/",
  },
  {
    type: "completed",
    title:
      "Quanglinhvlogs || Khoan Giếng Nước Sạch Cho Người Dân Bản Địa Châu Phi",
    date: "10/2023~10/2028",
    place: "",
    linkYT: "https://www.youtube.com/embed/LXcWjzaMwqE?si=6ubyy8q_rcOhWl15",
    des: "Clean water changes everything. charity: water brings clean and safe drinking water to people in need around the world, improving health, education, and opportunity - especially for women and children. 100% of public donations go directly to clean water projects. Clean water changes everything. charity: water brings clean and safe drinking water to people in need around the world, improving health, education, and opportunity - especially for women and children. 100% of public donations go directly to clean water projects.",
    amoutOfLikes: "106k",
    introductionFile: "https://www.facebook.com/",
    pitchFile: "https://www.facebook.com/",
    planFile: "https://www.facebook.com/",
    achievementFile: "https://www.facebook.com/",
    detailFile: "https://www.facebook.com/",
    cost: "10.000.000VND",
  },
  {
    type: "completed",
    title: "Lời Kêu Gọi Donate",
    date: "10/2023~10/2028",
    place: "Quang Binh",
    linkYT: "https://www.youtube.com/embed/sC2sEm0UBVQ?si=tpYTdgVVytiK_TlU",
    des: "Bạn hẳn sẽ không cầm lòng nổi khi biết ở vùng cao, vùng sâu, vùng xa có hàng trăm, hàng ngàn đồng bào của chúng ta đang sống cuộc sống nghèo khó, thiếu thốn. Người già, trẻ em không có nổi tấm chăn, manh áo ấm; các gia đình lay lắt bên những mái nhà xuống cấp không đủ che gió, che mưa; biết bao em bé không có sách để đọc, không có quyển vở cây bút để viết, thậm chí có em không được đến trường",
    amoutOfLikes: "798.8k",
    introductionFile: "https://www.facebook.com/",
    pitchFile: "https://www.facebook.com/",
    planFile: "https://www.facebook.com/",
    achievementFile: "https://www.facebook.com/",
    detailFile: "https://www.facebook.com/",
    cost: "10.000.000VND",
  },
];

export default Projects;
